

services:
  app:
    image: moufida12/mytestubuntu:latest
    container_name: jupyter_app
    ports:
      - "8888:8888"
    volumes:
      - projectdata:/workspace/projects
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123       
      POSTGRES_DB: toolsdb
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init_users.sql:/docker-entrypoint-initdb.d/init_users.sql

volumes:
  pgdata:
  projectdata:

